package calc4arduino.view;

import calc4arduino.Alimentacao;
import calc4arduino.LED;
import calc4arduino.Resistor;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor
 */
public class CalcularResistenciaNecessariaParaLEDs extends javax.swing.JFrame {

    /**
     * Creates new form CalculaValorMinimoDeResistorParaLED
     */
    public CalcularResistenciaNecessariaParaLEDs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboAlimentacao = new javax.swing.JComboBox();
        comboCorLED = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setTitle("Calcula Valor Resistência Necessária para LEDs");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel2.setText("Alimentação:");

        comboAlimentacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USB" }));

        comboCorLED.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vermelho", "Amarelo", "Laranja", "Verde", "Azul", "Branco" }));

        jLabel3.setText("Cor do LED:");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCorLED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAlimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboAlimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCorLED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        Alimentacao alimentacao = new Alimentacao();
        
        if (comboAlimentacao.getSelectedItem().toString() == Alimentacao.USB)
        {
            alimentacao.setTipoAlimentacao(Alimentacao.USB);
        }
        
        LED led = new LED();
        
        if (comboCorLED.getSelectedItem().toString() == "Vermelho")
        {
            led.setCorLED(LED.LED_VERMELHO);
        }
        else if (comboCorLED.getSelectedItem().toString() == "Amarelo")
        {
            led.setCorLED(LED.LED_AMARELO);
        }
        else if (comboCorLED.getSelectedItem().toString() == "Laranja")
        {
            led.setCorLED(LED.LED_LARANJA);
        }
        else if (comboCorLED.getSelectedItem().toString() == "Verde")
        {
            led.setCorLED(LED.LED_VERDE);
        }
        else if (comboCorLED.getSelectedItem().toString() == "Azul")
        {
            led.setCorLED(LED.LED_AZUL);
        }
        else if (comboCorLED.getSelectedItem().toString() == "Branco")
        {
            led.setCorLED(LED.LED_BRANCO);
        }
        
        Resistor resistor = new Resistor();
        JOptionPane.showMessageDialog(null, "A resistência necessária é " + resistor.calcularResistenciaNecessaria(alimentacao, led) + " ohms.");
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcularResistenciaNecessariaParaLEDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcularResistenciaNecessariaParaLEDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcularResistenciaNecessariaParaLEDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcularResistenciaNecessariaParaLEDs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcularResistenciaNecessariaParaLEDs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox comboAlimentacao;
    private javax.swing.JComboBox comboCorLED;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
